language: java
jdk:
- oraclejdk8
- oraclejdk7
- openjdk7
notifications:
  slack:
    secure: OgAHVQHkbkN/z5BVmuEBchaLB6dyNJNBDpsN1+DKOEktcEJs8jjeb4Y0YG88tCqa0avKcOYX0geuP/G2W+cOOwLRVGB2JpEGVb0uyGWxO5Nt3XrjRHqSJahB1dA8Q2E+dYFiiAaxx5ZkZ0zpzN0RBwHUSalVBvrzXmeqL2eMcbRGubNgJklpyPjHAZp5UqmzOmmKq3zSeWjBxU+J1D0fPJPJVmJCMp++uCv/0HMG3BIBJ7mpK0U8JAFojjLqzpBVho4ejhaMwWlg8B4S8wmpe/RcyNV2qQ+phuN6fdAzMFWmcz1B8WOZCO59G037M6FpCbnfw1n6kv5M216ZxsLNTZzj1xi0xFT4Y3GuaJMLekZyxPbv3pgRakms4abHLy9fTMZHVBaiwTuQrgDj7WEOz5PFZL9hcg+MacaT/Zr9wMfK198JvzCVOd6BRvstvX/31GvOhT5YvWct0f9FhYmqV1zvE34eaI6lok7B1BQdhFcUoKSyV5GZg+PItDLL+EF6LL1gf4DLD0tH+SUQvq2HbgmAc4uMO8XKQr3UDdZh6VKnfM4SuvzNjGbHNUNe56wo6DL56e8fh5pERoBiGdH+acCz1fXLycZsrPSajAk/Q5OmZIGwYH3N+yvKIK8UWxcNNfXfMjcbKUUMMvn0KsQpgkouC0H6SpnQ7FX2fW2H3x8=
