name: Skins
main: com.comze_instancelabs.skins.Main
version: 1.2
author: instancelabs
commands:
   skin:
      description: Builds a statue of the player
      usage: /skin
   statue:
      description: Builds a statue of the player
      usage: /statue
   colortest:
      description: Runs a colortest to determine all currently supported colors
      usage: /colortest